package com.travelhub.backend.repository;

import com.travelhub.backend.entity.Agent;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * AgentRepository handles database operations for the Agent entity.
 * It includes complex queries for performance analytics and agent searches.
 */
@Repository
public interface AgentRepository extends JpaRepository<Agent, Long> {

    // ── Agent Filters ─────────────────────────────────
    
    // Retrieves all agents whose profiles are currently active
    List<Agent> findByIsActiveTrue();

    // Retrieves agents based on their registration application status (e.g., Pending, Approved)
    List<Agent> findByApplicationStatus(String applicationStatus);

    // Performs a comprehensive search for agents by matching a keyword against user name, email, or company name
    @Query("SELECT a FROM Agent a JOIN a.user u WHERE " +
            "LOWER(u.name) LIKE LOWER(CONCAT('%', :keyword, '%')) OR " +
            "LOWER(u.email) LIKE LOWER(CONCAT('%', :keyword, '%')) OR " +
            "LOWER(a.companyName) LIKE LOWER(CONCAT('%', :keyword, '%'))")
    List<Agent> searchAgents(@Param("keyword") String keyword);


    // ── Analytics Queries ─────────────────────────────
    
    // Calculates the total revenue generated by an agent from completed bookings
    @Query("SELECT COALESCE(SUM(b.totalPrice), 0) " +
            "FROM Booking b " +
            "WHERE b.pkg.agent.id = :agentId " +
            "AND b.status = 'completed'")
    Double getTotalRevenueByAgentId(@Param("agentId") Long agentId);

    // Counts the total number of trips (bookings) associated with a specific agent
    @Query("SELECT COUNT(b) FROM Booking b " +
            "WHERE b.pkg.agent.id = :agentId")
    Long getTotalTripsByAgentId(@Param("agentId") Long agentId);

    // Calculates the average rating for an agent based on reviews of their packages
    @Query("SELECT COALESCE(AVG(r.rating), 0) " +
            "FROM Review r " +
            "WHERE r.pkg.agent.id = :agentId")
    Double getAvgRatingByAgentId(@Param("agentId") Long agentId);

    // Counts the total number of cancelled trips for a specific agent
    @Query("SELECT COUNT(b) FROM Booking b " +
            "WHERE b.pkg.agent.id = :agentId " +
            "AND b.status = 'cancelled'")
    Long getCancelledTripsByAgentId(@Param("agentId") Long agentId);

    // Calculates revenue for a specific month and year for an agent
    @Query("SELECT COALESCE(SUM(b.totalPrice), 0) " +
            "FROM Booking b " +
            "WHERE b.pkg.agent.id = :agentId " +
            "AND MONTH(b.createdAt) = :month " +
            "AND YEAR(b.createdAt) = :year " +
            "AND b.status = 'completed'")
    Double getMonthlyRevenueByAgentId(
            @Param("agentId") Long agentId,
            @Param("month") int month,
            @Param("year") int year
    );
}