-- Flyway migration V35: Restore all package entity columns in packages table
ALTER TABLE packages ADD COLUMN IF NOT EXISTS package_id VARCHAR(20);
ALTER TABLE packages ADD COLUMN IF NOT EXISTS start_place VARCHAR(255);
ALTER TABLE packages ADD COLUMN IF NOT EXISTS end_place VARCHAR(255);
ALTER TABLE packages ADD COLUMN IF NOT EXISTS duration VARCHAR(255);
ALTER TABLE packages ADD COLUMN IF NOT EXISTS category VARCHAR(255);
ALTER TABLE packages ADD COLUMN IF NOT EXISTS district VARCHAR(255);
ALTER TABLE packages ADD COLUMN IF NOT EXISTS package_type VARCHAR(255) DEFAULT 'SINGLE_DISTRICT';
ALTER TABLE packages ADD COLUMN IF NOT EXISTS price_from DOUBLE PRECISION;
ALTER TABLE packages ADD COLUMN IF NOT EXISTS price_to DOUBLE PRECISION;
ALTER TABLE packages ADD COLUMN IF NOT EXISTS base_price_adult DOUBLE PRECISION;
ALTER TABLE packages ADD COLUMN IF NOT EXISTS base_price_child DOUBLE PRECISION;
ALTER TABLE packages ADD COLUMN IF NOT EXISTS festival_details TEXT;
ALTER TABLE packages ADD COLUMN IF NOT EXISTS inclusions TEXT;
ALTER TABLE packages ADD COLUMN IF NOT EXISTS rejection_reason VARCHAR(1000);
ALTER TABLE packages ADD COLUMN IF NOT EXISTS trending BOOLEAN DEFAULT FALSE;
ALTER TABLE packages ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
