/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HotelsNewRouteImport } from './routes/hotels.new'
import { Route as HotelsHotelIdRouteImport } from './routes/hotels.$hotelId'
import { Route as DashboardHotelIdRouteImport } from './routes/dashboard.$hotelId'
import { Route as HotelsHotelIdEditRouteImport } from './routes/hotels.$hotelId.edit'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsNewRoute = HotelsNewRouteImport.update({
  id: '/hotels/new',
  path: '/hotels/new',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsHotelIdRoute = HotelsHotelIdRouteImport.update({
  id: '/hotels/$hotelId',
  path: '/hotels/$hotelId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardHotelIdRoute = DashboardHotelIdRouteImport.update({
  id: '/dashboard/$hotelId',
  path: '/dashboard/$hotelId',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsHotelIdEditRoute = HotelsHotelIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => HotelsHotelIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/dashboard/$hotelId': typeof DashboardHotelIdRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRouteWithChildren
  '/hotels/new': typeof HotelsNewRoute
  '/hotels/$hotelId/edit': typeof HotelsHotelIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/dashboard/$hotelId': typeof DashboardHotelIdRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRouteWithChildren
  '/hotels/new': typeof HotelsNewRoute
  '/hotels/$hotelId/edit': typeof HotelsHotelIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/dashboard/$hotelId': typeof DashboardHotelIdRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRouteWithChildren
  '/hotels/new': typeof HotelsNewRoute
  '/hotels/$hotelId/edit': typeof HotelsHotelIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/dashboard/$hotelId'
    | '/hotels/$hotelId'
    | '/hotels/new'
    | '/hotels/$hotelId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/dashboard/$hotelId'
    | '/hotels/$hotelId'
    | '/hotels/new'
    | '/hotels/$hotelId/edit'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/dashboard/$hotelId'
    | '/hotels/$hotelId'
    | '/hotels/new'
    | '/hotels/$hotelId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  DashboardHotelIdRoute: typeof DashboardHotelIdRoute
  HotelsHotelIdRoute: typeof HotelsHotelIdRouteWithChildren
  HotelsNewRoute: typeof HotelsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/new': {
      id: '/hotels/new'
      path: '/hotels/new'
      fullPath: '/hotels/new'
      preLoaderRoute: typeof HotelsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/$hotelId': {
      id: '/hotels/$hotelId'
      path: '/hotels/$hotelId'
      fullPath: '/hotels/$hotelId'
      preLoaderRoute: typeof HotelsHotelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$hotelId': {
      id: '/dashboard/$hotelId'
      path: '/dashboard/$hotelId'
      fullPath: '/dashboard/$hotelId'
      preLoaderRoute: typeof DashboardHotelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/$hotelId/edit': {
      id: '/hotels/$hotelId/edit'
      path: '/edit'
      fullPath: '/hotels/$hotelId/edit'
      preLoaderRoute: typeof HotelsHotelIdEditRouteImport
      parentRoute: typeof HotelsHotelIdRoute
    }
  }
}

interface HotelsHotelIdRouteChildren {
  HotelsHotelIdEditRoute: typeof HotelsHotelIdEditRoute
}

const HotelsHotelIdRouteChildren: HotelsHotelIdRouteChildren = {
  HotelsHotelIdEditRoute: HotelsHotelIdEditRoute,
}

const HotelsHotelIdRouteWithChildren = HotelsHotelIdRoute._addFileChildren(
  HotelsHotelIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  DashboardHotelIdRoute: DashboardHotelIdRoute,
  HotelsHotelIdRoute: HotelsHotelIdRouteWithChildren,
  HotelsNewRoute: HotelsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
