package com.travelhub.backend.entity;

import jakarta.persistence.*;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Agent entity represents a travel agent or agency in the system.
 * It extends the basic User functionality with specific business details.
 */
@Entity
@Table(name = "agents", schema = "public")
public class Agent {
    // Unique identifier, mapped from the associated user's ID
    @Id
    private Long id;

    // One-to-one relationship with the User entity. 
    // Uses @MapsId to share the same primary key as the User.
    @OneToOne(fetch = FetchType.LAZY)
    @MapsId
    @JoinColumn(name = "user_id")
    private User user;

    // The registered name of the agency
    private String agencyName;
    
    // Official travel agent license number
    private String licenseNumber;
    
    // Legal company name
    private String companyName;
    
    // Name of the company owner
    private String ownerName;
    
    // Additional contact phone number
    private String secondaryPhone;
    
    // WhatsApp number for quick communication
    private String whatsappNumber;
    
    // Physical location or headquarters of the agency
    private String location;
    
    // Short biography or description of the agency
    private String bio;
    
    // Languages supported by the agent/agency
    private String languages;
    
    // Geographic districts where the agency operates
    private String operatingDistricts;
    
    // Link to the agency's official website
    private String websiteUrl;
    
    // Date since the agent has been a member of the platform
    private LocalDate memberSince;
    
    // URL or path to the NIC (National Identity Card) image for verification
    private String nicImageUrl;
    
    // Current status of the agent's application (e.g., Pending, Approved)
    private String applicationStatus = "Pending";
    
    // Timestamp of when the application was submitted
    private LocalDateTime submittedDate;
    
    // Overall user rating for the agent
    private Double rating;
    
    // Total number of trips organized/completed by this agent
    private Integer totalTrips;
    
    // Aggregated revenue generated by the agent
    private Integer totalRevenue;
    
    // Number of years of experience in the travel industry
    private Integer experienceYears;
    
    // Percentage rate of successfully completed trips
    private Double completionRate;
    
    // Flag indicating if the agent profile is active
    private Boolean isActive = true;

    /**
     * Default constructor for JPA.
     */
    public Agent() {}

    // --- Getters and Setters ---

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }
    public User getUser() { return user; }
    public void setUser(User user) { this.user = user; }
    public String getAgencyName() { return agencyName; }
    public void setAgencyName(String agencyName) { this.agencyName = agencyName; }
    public String getLicenseNumber() { return licenseNumber; }
    public void setLicenseNumber(String licenseNumber) { this.licenseNumber = licenseNumber; }
    public String getCompanyName() { return companyName; }
    public void setCompanyName(String companyName) { this.companyName = companyName; }
    public String getOwnerName() { return ownerName; }
    public void setOwnerName(String ownerName) { this.ownerName = ownerName; }
    public String getSecondaryPhone() { return secondaryPhone; }
    public void setSecondaryPhone(String secondaryPhone) { this.secondaryPhone = secondaryPhone; }
    public String getWhatsappNumber() { return whatsappNumber; }
    public void setWhatsappNumber(String whatsappNumber) { this.whatsappNumber = whatsappNumber; }
    public String getLocation() { return location; }
    public void setLocation(String location) { this.location = location; }
    public String getBio() { return bio; }
    public void setBio(String bio) { this.bio = bio; }
    public String getLanguages() { return languages; }
    public void setLanguages(String languages) { this.languages = languages; }
    public String getOperatingDistricts() { return operatingDistricts; }
    public void setOperatingDistricts(String operatingDistricts) { this.operatingDistricts = operatingDistricts; }
    public String getWebsiteUrl() { return websiteUrl; }
    public void setWebsiteUrl(String websiteUrl) { this.websiteUrl = websiteUrl; }
    public LocalDate getMemberSince() { return memberSince; }
    public void setMemberSince(LocalDate memberSince) { this.memberSince = memberSince; }
    public String getNicImageUrl() { return nicImageUrl; }
    public void setNicImageUrl(String nicImageUrl) { this.nicImageUrl = nicImageUrl; }
    public String getApplicationStatus() { return applicationStatus; }
    public void setApplicationStatus(String applicationStatus) { this.applicationStatus = applicationStatus; }
    public LocalDateTime getSubmittedDate() { return submittedDate; }
    public void setSubmittedDate(LocalDateTime submittedDate) { this.submittedDate = submittedDate; }
    public Double getRating() { return rating; }
    public void setRating(Double rating) { this.rating = rating; }
    public Integer getTotalTrips() { return totalTrips; }
    public void setTotalTrips(Integer totalTrips) { this.totalTrips = totalTrips; }
    public Integer getTotalRevenue() { return totalRevenue; }
    public void setTotalRevenue(Integer totalRevenue) { this.totalRevenue = totalRevenue; }
    public Integer getExperienceYears() { return experienceYears; }
    public void setExperienceYears(Integer experienceYears) { this.experienceYears = experienceYears; }
    public Double getCompletionRate() { return completionRate; }
    public void setCompletionRate(Double completionRate) { this.completionRate = completionRate; }
    public Boolean getIsActive() { return isActive; }
    public void setIsActive(Boolean isActive) { this.isActive = isActive; }

    /**
     * Life-cycle hook to set the submission date before persisting if it's null.
     */
    @PrePersist
    protected void onCreate() {
        if (submittedDate == null) {
            submittedDate = LocalDateTime.now();
        }
    }
}